# mise configuration for dotfiles dependencies
# This file installs all tools required by the zsh configuration

[tools]
delta = "latest"
direnv = "latest"
dotnet = "latest"
fzf = "latest"
ghq = "latest"
go = "latest"
neovim = "latest"
node = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
pandoc = "latest"
ripgrep = "latest"
starship= "latest"
tmux = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
